name: clipboard_privacy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.0
  json_annotation: ^4.9.0
  nameof_annotation: ^0.2.1
  path: ^1.9.0
  receive_sharing_intent: ^1.8.0
  sqflite: ^2.3.3+2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  nameof: ^0.2.2

flutter:
  uses-material-design: true
